# Generated by Django 3.2.9 on 2022-11-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='redirect_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='link',
            field=models.TextField(unique=True),
        ),
    ]
