# Generated by Django 3.2.9 on 2022-11-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221101_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallinksignup',
            name='action_completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrallinksignup',
            name='amount_deposited',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
