# Generated by Django 3.2.9 on 2022-11-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221104_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallinksignup',
            name='first_deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrallinksignup',
            name='program_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='referrallinksignup',
            name='reward_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrallinksignup',
            name='twab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='link',
            field=models.TextField(),
        ),
    ]
