# Generated by Django 3.2.9 on 2022-11-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221105_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallinksignup',
            name='amount_deposited',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='referrallinksignup',
            name='reward_earned',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='referrallinksignup',
            name='twab',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
